apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: "/spec/url/hostname"
        value: 'kunde.felleskomponent.no'
    target:
      kind: Application
      name: fint-kunde-portal-frontend
