apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kunde-portal-frontend-old
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-kunde-portal-frontend-old
    app.kubernetes.io/instance: fint-kunde-portal-frontend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  env:
    - name: BASE_PATH
      value: http://fint-kunde-portal-backend:8080
    - name: LINKWALKER_API_URL
      value: http://fint-link-walker:8080
    - name: CONSENT_API_URL
      value: http://fint-samtykke-admin-backend:8080
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kunde-portal-frontend:latest
  url:
    hostname: kunde-old.felleskomponent.no
    basePath: /
  ingress:
    enabled: true
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
  restartPolicy: Always
  replicas: 1
#  strategy:
#    type: RollingUpdate
#    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }